name: Run benchmarks

on:
  pull_request:
    types: [labeled, opened, synchronize, reopened]

jobs:
  benchmark:
    runs-on: ubuntu-latest
    env:
      JULIA_DEBUG: BenchmarkCI
      # Add project root directory `.` to the load path:
      JULIA_LOAD_PATH: '@:.:'
    if: contains(github.event.pull_request.labels.*.name, 'run benchmark')
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: 1.5
      - name: Install dependencies
        run: julia -e 'using Pkg; pkg"add PkgBenchmark BenchmarkCI@0.1"'
      - name: Run benchmarks
        run: julia -e '
          using PkgBenchmark, BenchmarkCI;
          BenchmarkCI.judge(
              PkgBenchmark.BenchmarkConfig(
                  env = Dict("JULIA_NUM_THREADS" => "1"),
              );
          );
          '
      - name: Post results
        run: julia -e 'using BenchmarkCI; BenchmarkCI.postjudge()'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
